Messages:
  Reload: "§#3ede91Конфигурация перезагруженна!"
  Back: "§#3ede91Вы вернулись на прежную локацию."
  Teleport:
    not-online: "§#f75270%player% не в сети."
    no-queries: "§#f75270У вас нет активных запросов на телепортацию"
    self-teleport: "§#f75270Вы не можете телепортироваться к себе."
    accepted-target: "§#3ede91Вы телепортировались к игроку %player%"
    accepted-sender: "§#3ede91Вы телепортировали игрока %player%"
    denied-target: "§#ff75270%player% отклонил ваш запрос на телепортацию"
    denied-sender: "§#f7dc52Вы отклонили запрос на телепортацибю игрока %player%"
    usage: "§#f7dc52Использование команды: /teleport ник_игрока"
    query: "К вам хочет телепортироваться §#f7dc52%player%."
    accept_button: "§#3ede91[принять]"
    space_between: " "
    deny_button: "§#f75270[отклонить]"
    accept_hover: "§#f7dc52Принять запрос на телепортацию от %player%"
    deny_hover: "§#f7dc52Отклонить запрос на телепортацию от %player%"
  Speed:
    fly-speed: "Скорость полета: §#f7dc52%speed%"
    walk-speed: "Скорость ходьбы: §#f7dc52%speed%"
    scroll-off: "Прокрутка скорости §#f75270отключена"
    scroll-on: "Прокрутка скорости §#3ede91включена"
    usage: "Использование команды: §#f7dc52/speed toggle §#ffffffили §#f7dc52/speed 1-10"
    usage-scroll: "Изменить скорость: §#f7dc52shift + scroll§#ffffff. Отключить: §#f7dc52/speed toggle"
  Waypoint:
    teleport: "§#3ede91Вы телепортировались к метке"
    usage: "Использование команды: §#f7dc52/waypoint toggle|clear|last|set §#ffffffили §#f7dc52/waypoint число"
    saved: "§#3ede91Метка телепортации №%count% сохранена."
    max: "§#f75270Вы можете поставить максимум 10 меток телепортации."
    cleared: "§#f7dc52Метки телепортации отчищены."
    using-f-off: "Использование клавиши f для метки телепортации §#f75270отключена"
    using-f-on: "Использование клавиши f для метки телепортации §#3ede91включена"
    not-exist: "§#f75270Вы не создавали меток или такой метки не существует!"